Edit expense possibility
JakubOciepa/Contador pull request #26
Opened 2021-03-14 13:30 UTC by JakubOciepa

Add possibility to edit existing expense from the Expenses page. 

Closing #24

2021-03-14 14:21 UTC, ShanSanear commented on src/Contador.Web/Client/Components/ExpenseComponent.razor.cs
> +					await _jsRuntime.InvokeVoidAsync("alert", "Expense has been updated!");
Maybe switch this to some kind of banner at the top, instead of alert popup? If you want to edit few items, there is no need to give feedback that it has been edited successfully and block from changing other expenses

2021-03-14 14:24 UTC, ShanSanear commented on src/Contador.Web/Client/Components/ExpenseComponent.razor.cs
> +					await _jsRuntime.InvokeVoidAsync("alert", "Cannot update expense!");
The same goes for this message in case of an error

2021-03-14 14:25 UTC, ShanSanear commented on src/Contador.Web/Client/Components/ExpenseComponent.razor.cs
> +				await _jsRuntime.InvokeVoidAsync("alert", "Cannot update expense!");
Maybe providing some message and again - as banner? Maybe with type of exception or something? Or as scrollable traceback?

2021-03-14 14:26 UTC, ShanSanear commented on src/Contador.Web/Client/Components/ExpenseComponent.razor.cs
> +		private object CreateHttpBody()
HTTP Body of what? Also its not Http body in itself, just object

2021-03-14 14:27 UTC, ShanSanear commented on src/Contador.Web/Client/Pages/Expenses.razor
> +				<th></th>
Is this needed?

2021-03-14 14:28 UTC, ShanSanear commented on src/Contador.Web/Client/Pages/Expenses.razor.cs
> +		private object CreateHttpBody()
Again - name seems to say something about creating Http body, while in reality this is creation of object instead

2021-03-14 14:29 UTC, ShanSanear requested changes
As per comments, some issues have been found

2021-03-14 19:10 UTC, JakubOciepa commented on src/Contador.Web/Client/Components/ExpenseComponent.razor.cs
> +					await _jsRuntime.InvokeVoidAsync("alert", "Expense has been updated!");
I'll change this. But I'll left this for now because currently I don't know how I want to change it. I'm thinking about something like this https://demos.telerik.com/blazor-ui/notification/overview but I still want to think about it. Right now I would like to focus on the main functionalities. UI and UX would be the next steps.

2021-03-14 19:10 UTC, JakubOciepa commented on src/Contador.Web/Client/Components/ExpenseComponent.razor.cs
> +					await _jsRuntime.InvokeVoidAsync("alert", "Cannot update expense!");
As above.

2021-03-14 19:11 UTC, JakubOciepa commented on src/Contador.Web/Client/Components/ExpenseComponent.razor.cs
> +				await _jsRuntime.InvokeVoidAsync("alert", "Cannot update expense!");
As above.

2021-03-14 19:12 UTC, JakubOciepa commented on src/Contador.Web/Client/Components/ExpenseComponent.razor.cs
> +		private object CreateHttpBody()
Changed.

2021-03-14 19:12 UTC, JakubOciepa commented on src/Contador.Web/Client/Pages/Expenses.razor.cs
> +		private object CreateHttpBody()
Changed.

2021-03-14 19:23 UTC, JakubOciepa commented on src/Contador.Web/Client/Pages/Expenses.razor
> +				<th></th>
Changed 😁

2021-03-16 16:27 UTC, ShanSanear approved these changes

2021-03-16 16:28 UTC, merged